import{a as l,i as p,S as f}from"./assets/vendor-22d9b643.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();l.defaults.headers.common["x-api-key"]="live_sQSiU8IUrkSu8g32YTEYKLB8DcWcIsBNMk0omc8QjPKH9Bo7QndZdmjMVf3YCCwv";l.defaults.baseURL="https://api.thecatapi.com/v1";function m(){return l.get("/breeds").then(e=>e.data)}function L(e){return l.get(`/images/search?breed_ids=${e}`).then(n=>n.data[0])}const c={LS_KEY_OPTION:"user-option",PLACEHOLDER_LOADING:"Loading...",PLACEHOLDER_SUCCESS:"Select a cat breed...",PLACEHOLDER_ERROR:"Breeds not found..."};function u(e){p.error({message:e,position:"topCenter"})}const h=e=>`
  <img class="cat-img" src="${e.url}" alt="" />
  <div class="cat-text">
    <h1 class="cat-title">${e.breeds[0].name}</h1>
    <p>${e.breeds[0].description}</p>
    <p><span class="cat-temp">Temperament:</span> ${e.breeds[0].temperament}</p>
  </div>`,g=e=>`
  <p class="error">Oops! ${e} not found :(<br>Try reloading the page!</p>`,o={container:document.querySelector(".cat-info"),spinner:document.querySelector(".loader-spinner")};function y(e){o.container.innerHTML="",o.container.style.opacity="0",o.spinner.style.display="block",L(e.value).then(n=>{o.container.innerHTML=h(n)}).catch(n=>{o.container.innerHTML=g(e.text),u(n.message)}).finally(()=>{o.spinner.style.display="none",o.container.style.opacity="1"})}function E([e]){e.placeholder||(y(e),localStorage.setItem(c.LS_KEY_OPTION,e.value))}const s=new f({select:"#select",settings:{disabled:!0,placeholderText:c.PLACEHOLDER_LOADING},events:{afterChange:E}});function O(e){s.enable(),s.setData([{placeholder:!0,text:c.PLACEHOLDER_SUCCESS},...e])}function S(e){s.setSelected(e)}function C(){s.disable(),s.setData([{placeholder:!0,text:c.PLACEHOLDER_ERROR}])}function b(){m().then(e=>{const n=e.map(({id:i,name:t})=>({text:t,value:i}));O(n);const a=localStorage.getItem(c.LS_KEY_OPTION);a&&S(a)}).catch(e=>{C(),u(e.message)})}document.addEventListener("DOMContentLoaded",b);
//# sourceMappingURL=commonHelpers.js.map
