import{a,i as l,S as d}from"./assets/vendor-454b0ffd.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();a.defaults.headers.common["x-api-key"]="live_sQSiU8IUrkSu8g32YTEYKLB8DcWcIsBNMk0omc8QjPKH9Bo7QndZdmjMVf3YCCwv";a.defaults.baseURL="https://api.thecatapi.com/v1";function u(){return a.get("/breeds").then(e=>e.data)}function p(e){return a.get(`/images/search?breed_ids=${e}`).then(n=>n.data[0])}function f(e){l.error({message:e,position:"center",timeout:3e4,progressBar:!1,close:!1,buttons:[["<button>OK</button>",function(n,o){n.hide({transitionOut:"fadeOutUp"},o)}]]})}const m=e=>`
  <img class="cat-img" src="${e.url}" alt="" />
  <div class="cat-text">
    <h1 class="cat-title">${e.breeds[0].name}</h1>
    <p>${e.breeds[0].description}</p>
    <p><span class="cat-temp">Temperament:</span> ${e.breeds[0].temperament}</p>
  </div>`,y=e=>`
  <p class="error">Oops! ${e} not found :(<br>Try reloading the page!</p>`,s={container:document.querySelector(".cat-info"),spinner:document.querySelector(".loader-spinner")};function h(e){s.container.innerHTML="",s.container.style.opacity="0",s.spinner.style.display="block",p(e.value).then(n=>{s.container.innerHTML=m(n)}).catch(()=>{s.container.innerHTML=y(e.text)}).finally(()=>{s.spinner.style.display="none",s.container.style.opacity="1"})}const g=document.querySelector(".loader-spinner");function b(){u().then(e=>{const n=e.map(({id:o,name:i})=>({text:i,value:o}));new d({select:"#select",data:[{placeholder:!0,text:"Select a cat breed..."},...n],events:{afterChange:([o])=>{h(o)}}})}).catch(()=>{f("Please try again later...")}).finally(()=>{g.style.display="none"})}document.addEventListener("DOMContentLoaded",b);
//# sourceMappingURL=commonHelpers.js.map
